[project]
name = "excel-001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.16.0",
    "polars>=1.35.2",
]
